// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinId } from "./BinId";
import type { BinQuality } from "./BinQuality";
import type { ContigAssignment } from "./ContigAssignment";

export type Bin = { id: BinId, contig_metadata: Array<ContigAssignment>, completeness: number | null, contamination: number | null, quality: BinQuality | null, };
