// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContigAssignment } from "./ContigAssignment";

export type ContigMetadata = { contig_id: string, bin: string, assignment: ContigAssignment, mean_coverage: number, n_motif_obs: number, note: string | null, };
