// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assignment } from "./Assignment";

export type ContigMetadata = { contig_id: string, assignment: Assignment, mean_coverage: number, note: string | null, };
