// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assignment } from "./Assignment";
import type { ContigId } from "./ContigId";

export type ContigAssignment = { contig_id: ContigId, assignment: Assignment, };
