// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContigMetadata } from "./ContigMetadata";

export type HeatmapData = { contigs: Array<string>, motifs: Array<string>, matrix: Array<Array<number | null>>, metadata: { [key in string]?: ContigMetadata }, };
