// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinId } from "./BinId";
import type { ContigAssignment } from "./ContigAssignment";

export type MetadataUpdate = { bin: BinId, contigs: Array<ContigAssignment>, };
