// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MethDataFilters = { contigs: Array<string>, min_n_motif_obs: number | null, min_motif_variance: number | null, min_coverage: number | null, };
