// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectDetails = { project_id: string, methylation_data_path: string, contig_bin_path: string, bin_quality_path: string | null, output_path: string, };
